spring:
  config:
    import: classpath:privacy.yml
    activate:
      on-profile: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

logging:
  file:
    path: ${user.dir}/log
    name: ${user.dir}/log/formssafe
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{traceId}] %highlight(%-5level) %cyan(%logger{36}.%M) - %msg%n"
  level:
    com:
      formssafe:
        debug