spring:
  config:
    import: classpath:privacy.yml
    activate:
      on-profile: local
  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
=======
      ddl-auto: update
>>>>>>> a72edcc133cd75210271c57c35ad92247a234072

logging:
  file:
    path: ${user.dir}/log
    name: ${user.dir}/log/formssafe
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{traceId}] %highlight(%-5level) %cyan(%logger{36}.%M) - %msg%n"
  level:
    com:
      formssafe: debug