### 내가 참여한 설문에서 나의 응답 조회
GET http://localhost:80/api/v1/activity/forms/1/responses
Cookie: SESSION_ID=YjBmNTYxNTMtMTYxMS00ZjBiLTlkODktZWM2ZmI5MTRkOTJi;

### 내가 등록한 설문 전체 조회
GET http://localhost:80/api/v1/activity/forms?keyword=form&sort=responseCnt&category=c1,c2,c3&status=progress&tag=t1,t2&
    pageNum=10
Cookie: SESSION_ID=YjBmNTYxNTMtMTYxMS00ZjBiLTlkODktZWM2ZmI5MTRkOTJi;

### 내가 참여한 설문 전체 조회
GET http://localhost:80/api/v1/activity/responses?keyword=form&sort=responseCnt&category=c1,c2,c3&status=progress&
    tag=t1,t2&
    pageNum=10
Cookie: SESSION_ID=YjBmNTYxNTMtMTYxMS00ZjBiLTlkODktZWM2ZmI5MTRkOTJi;